Strategies:
  - id: SAMPLE-1
    name: Sample strategy 1
    strategy_class: elena_sample.strategy_trailing_stop_with_bb.trailing_stop_bb.TrailingStopLossBBbuyAfterSleep
    enabled: true
    bots:
      - id: SAM-1.1
        name: Sample strategy 1 bot 1
        enabled: true
        pair: ETH/USDT
        exchange: kucoin
        tags:
          - ranging
          - bear
        config:
          key1: value1
          key2: value2
      - id: SAM-1.2
        name: Sample strategy 1 bot 2
        enabled: false
        pair: BTC/USDC
        exchange: bitget
        tags:
          - bull
        config:
          key1: value1
          key2: value2
Exchanges:
  - id: bitget
    enabled: true
    sandbox_mode: true
    api_key: ***REMOVED***
    password: ***REMOVED***
    secret: ***REMOVED***
  - id: kucoin
    enabled: true
    sandbox_mode: false
    api_key: ***REMOVED***
    password: ***REMOVED***
    secret: ***REMOVED***
Tags:
  - id: bear
    enabled: true
  - id: bull
    enabled: false
  - id: ranging
    enabled: true