Strategies:
  - id: TrailingStopLoss
    name: TrailingStopLoss
    enabled: true
    strategy_class: elena_sample.strategy_trailing_stop_with_bb.trailing_stop_bb.TrailingStopLoss

    bots:
      - id: BTC_USDT_1
        name: TrailingStopLoss BTC/USDT
        enabled: true
        pair: BTC/USDT
        exchange: binance
        tags:
          - TrailingStopLoss
          - bear
        config:
          band_length: 3
          band_mult: 3
          initial_sl_factor: 0
          sl_limit_price_factor: 0.01 # % of price limit on the sl limit order. it's used for minimal benefit too.
          asset_to_manage: 100%


Exchanges:
  - id: binance
    enabled: true
    sandbox_mode: true
    api_key: ***REMOVED***
    password: not_in_use
    secret: ***REMOVED***
  - id: bitget
    enabled: true
    sandbox_mode: true
    api_key: ***REMOVED***
    password: ***REMOVED***
    secret: ***REMOVED***
  - id: kucoin
    enabled: true
    sandbox_mode: false
    api_key: ***REMOVED***
    password: ***REMOVED***
    secret: ***REMOVED***

Tags:
  - id: bear
    enabled: true
  - id: bull
    enabled: false
  - id: ranging
    enabled: true
  - id: TrailingStopLoss
    enabled: true

CctxExchangeManager:
  fetch_ohlcv_limit: 100
  fetch_ohlcv_limit_retry_every_milliseconds: 1000